//
//  Program.swift
//  PULSE Program
//
//  Created by Michelle Krameisen on 11/28/17.
//  Copyright © 2017 Krameisen. All rights reserved.
//

import Foundation
import UIKit

class Program {
    var name: String!
    var description: String!
    var supervisor: String!
    var latitude: CGFloat!
    var longitude: CGFloat!
    init(name: String, description: String, supervisor: String, latitude: CGFloat, longitude: CGFloat) {
        self.name = name
        self.description = description
        self.supervisor = supervisor
        self.latitude = latitude
        self.longitude = longitude
    }
}
class Programs {
    var programs: [Program] = []
    init() {
        self._826Boston()
        self.AFaithThatDoesJustice()
        self.ABCDAllstonBrighton()
        self.ABCDCentralOffice()
        self.ABCDDorchester()
        self.ABCDMattapan()
        self.BirdStreet()
        self.BCYF()
        self.BostonHealthCare()
        self.Bridge()
        self.CampusSchool()
        self.CareerCollaborative()
        self.Casa()
        self.Catholic()
        self.Charlesview()
        self.CollabEd()
        self.Collegebound()
        self.Crossroads()
        self.East()
        self.Elders()
        self.EDG()
        self.HAPHI()
        self.Haley()
        self.Italian()
        self.James()
        self.JVS()
        self.Little()
        self.Nativity()
        self.NWWC()
        self.NotreDame()
        self.Paraclete()
        self.PBread()
        self.Pine()
        self.PPlace()
        self.Rosie()
        self.Roxbury()
        self.Samaritans()
        self.Scholar()
        self.StFrancis()
        self.StMarks()
        self.StMarys()
        self.StStephens()
        self.Suffolk()
        self.Tenacity()
        self.United()
        self.VPBLC()
        self.VPLarc()
        self.VPShepherd()
        self.VPVictory()
        self.WestEnd()
        self.WFYP()
        
    }
    func getPrograms() -> [Program] {
        return self.programs
    }
    func _826Boston() {
        let program = Program(name: "826 Boston", description: "826 Boston is a nonprofit youth writing and publishing organization that empowers traditionally underserved students ages 6-18 to find their voices, tell their stories, and gain communication skills to succeed in school and in life. Our services are structured around the understanding that great leaps in learning can happen with one-on-one attention and that strong writing skills are fundamental to future success. With this understanding in mind, we provide after-school tutoring, field trips, creative writing workshops, in-school tutoring, help for English Language Learners, and in-depth publishing projects.Each of our free programs seeks to empower students to express their ideas effectively, creatively, confidently, and in their individual voices.", supervisor: "Jennifer Javier, Karen Sama", latitude: 42.316854, longitude:  -71.097706)
        self.programs.append(program)
    }
    func AFaithThatDoesJustice() {
        let program = Program(name: "A Faith That Does Justice", description: "A Faith That Does Justice is a 501(c)(3) non-profit ecumenical program that offers opportunities to live faith in action by reaching out to those in need and raising the consciousness of others about the social issues that affect our city and country. We welcome people of all races, religions, cultures and sexual orientations who desire to learn from each other and overcome the social, political and economic barriers that separate us. Our program has three components: 1. Workshops - take place at 300 Newbury St, Boston, MA, 02115. They explore faith lived in action on behalf of the unfinished work of the kingdom of God. Emphasis is placed on incarnating its core values of love, compassion for human suffering, and justice for all God’s people. These sessions are offered in English and Spanish and include a variety of themes. 2. Town Hall Meetings - take place at the Episcopal Cathedral Church of St. Paul, 138 Tremont St., Boston, MA 02111. They focus on social issues that affect the most vulnerable among us. These meetings are open to all and include invited speakers, discussion groups, and an opportunity for those in need to seek advice or assistance from non-profit organizations in attendance. Others will have an opportunity to volunteer their time with these, or other, organizations. We use simultaneous translation so that all understand the presentation and are able to participate in the discussion that follows from it. 3. Faith in Action - will be driven by participants from A Faith That Does Justice and focus on the works of mercy. We hope to initiate this effort during the coming year and are currently exploring funding, several possibilities for action (i.e., ESL, clothing distribution, ministry to the detained/imprisoned, etc.), and a location site.", supervisor: "Peter W. Gyves, SJ, MD", latitude: 42.348967, longitude: -71.084883)
        self.programs.append(program)
    }
    func ABCDAllstonBrighton() {
        let program = Program(name: "ABCD Allston-Brighton Neighborhood Community Center", description: "Action for Boston Community Development, Inc. (ABCD) seeks to end the hopeless and debilitating effects of poverty. ABCD Allston-Brighton NOC opened its doors in 2012 and is in the process of continuing to develop effective programs, service, and partnerships to provide resources to the residents of the Allston-Brighton Neighborhoods. Allston-Brighton NOC (A-B NOC) helps its clients access food, clothing, job search and housing support. Additionally, A-B NOC assists clients one on one to apply for SNAP, MassHealth, fuel assistance, tax benefits, and summer jobs. A-B NOC works closely with families experiencing homelessness and living in the motels in Brighton.", supervisor: "Amelia Youngstrom, Yuliya Lantsman", latitude: 42.350968, longitude: -71.169194)
        self.programs.append(program)
    }
    func ABCDCentralOffice() {
        let program = Program(name: "ABCD Central Office", description: "Action for Boston Community Development, Inc. (ABCD) was incorporated in 1962, as part of a national movement to end the hopeless and debilitating effects of poverty.Today ABCD serves more than 94,000 low-income Boston-area residents through its central offices and network of Neighborhood Service Centers (NSCs), Head Start centers, Family Planning sites and Foster Grandparent sites. Programs and affiliations include Fuel Assistance; Head Start; Child Care Services; Education; Career Development; Housing and Homelessness Services; Health Services; Family Planning; Urban College of Boston; University High – an Alternative High School; Ostiguy High School for high school students in recovery; Weatherization; Foster Grandparents; Elder Services; Intergenerational Programs; Food Pantries; advocacy and consumer services.Our Field Operations team oversees the operation of the NSC sites across Boston, Medford, Malden, and Everett. This team provides support, coordination as well as direct client services. We are looking for 4-6 students to learn about and assist us in this unique opportunity to provide operation support to the citywide operations of a major non profit. Students will also work directly with donors and clients in order to fully understand program operations more fully.Programs that students can expect to gain experience include our food pantry, fuel assistance program, winter clothing campaign, holiday food drive, holiday toy drive and tax preparation.", supervisor: "Amber Dickerson, Eric Michael", latitude: 42.353075, longitude: -71.064109)
        self.programs.append(program)
    }
    func ABCDDorchester() {
        let program = Program(name: "ABCD Dorchester Neighborhood Center", description: "Action for Boston Community Development, Inc. (ABCD) seeks to end the hopeless and debilitating effects of poverty.ABCD Dorchester NSC provides food, education, job training and jobs, advocacy and income relief for thousands of the residents of Dorchester.Action for Boston Community Development’s (ABCD) mission is to empower low-income people by providing them with the tools to overcome poverty, live with dignity, and achieve their full potential. The organization provides services for families and individuals throughout their lifespan. Services include Head Start, child care services, youth employment and career exploration, two alternative high schools, health programs and family planning, fuel assistance and weatherization, adult basic education and ESOL, vocational training and job placement, financial literacy, elder services, and free Tax preparation. ABCD Dorchester NSC is one of 15 neighborhood-based services centers that provide the mentioned direct services and can refer clients to other site or agencies if we don’t happen to offer a particular service. Health, fuel assistance, summer job and tax benefits. In some cases, we refer clients to other neighborhood resources.", supervisor: "Kathy Vo, Durrell Harris", latitude: 42.296184, longitude: -71.070893)
        self.programs.append(program)
    }
    func ABCDMattapan() {
        let program = Program(name: "ABCD Mattapan Family Service Center", description: "Action for Boston Community Development, Inc. (ABCD) seeks to end the hopeless and debilitating effects of poverty.ABCD Mattapan provides services to families in the Mattapan area that include ESOL classes, foreclosure prevention counseling, fuel assistance, and tax filing assistance. Services unique to the ABCD Mattapan location include: Senior Services weekly exercise classes, educational classes, recreational activities and group outings, Senior Brown Bag food and nutrition program for the elderly, Senior Day Trips, Senior Education Workshops, Senior Exercise Workshops. Mattapan United is a comprehensive Community development initiative that aims at improving the quality of life for people who live and work in Mattapan. The initiative brings together stakeholders in the Mattapan community to strategize ways to improve Mattapan and what their role should be. The idea is that community change should but community led. There are focus groups, leadership teams, informational meetings and a variety of ways for people to get involved and stay at the forefront of movement in their community. It is a great avenue for volunteerism and also encourages civic engagement.", supervisor: "Bianny Suncar, Cynthia Lee", latitude: 42.267353, longitude: -71.095406)
        self.programs.append(program)
    }
    func BirdStreet() {
        let program = Program(name: "Bird Street Community Center", description: "The mission of Bird Street is to instill in our youth and young adults the intellectual, social, and leadership competencies to deal effectively with daily challenges, strive for academic success, and pursue employment opportunities. Bird Street Community Center meets the day-to-day needs for building strong minds, healthy bodies and outlets for creative expression and social interaction for families and children. Bird Street enables individuals across generations to engage in educational activities and life-long learning. Bird Street is a second home for our members, providing space for local events, community gatherings, and celebrations. Bird Street serves mostly 12-18 year olds, but overall ages range from 10-22 years. The community center has a basketball court, lounge area, art area, dance room, homework room and computer room all open to the students.", supervisor: "Donna Woodson", latitude: 42.315073, longitude: -71.067712)
        self.programs.append(program)
    }
    func BCYF() {
        let program = Program(name: "BCYF Mildred Ave. Community Center", description: "The BCYF Mildred Avenue Community Center is part of Boston Centers for Youth and Families’ (BCYF) network of 35 facilities. The mission of Boston Centers for Youth & Families (BCYF) is to enhance the quality of life of Boston’s residents by partnering with various organizations to offer a wide range of comprehensive programs and activities according to neighborhood needs and interests.BCYF Mildred is home to an auditorium, community room, computer lab, dance studio, gymnasium, music studio, pool, and other facilities hosting a variety of programs and activities. There are programs for both adults and children in the community, varying for Tae Kwon Do, dance, swim lessons, and drama. The center is also home to a licensed after-school program that coordinates with the Mildred School to ensure students have sufficient after-school academic support.", supervisor: "Valerie Scales", latitude: 42.277105, longitude: -71.090607)
        self.programs.append(program)
    }
    func BostonHealthCare() {
        let program = Program(name: "Boston Healthcare for the Homeless Program", description: "The mission of Boston Health Care for the Homeless has remained the same: to provide or assure access to the highest quality health care for all homeless men, women and children in the greater Boston area. We believe it has been and continues to be medicine that matters. The core population served by BHCHP is adults and families experiencing homelessness who stay in the emergency shelter system, eat in soup kitchens, or visit drop-in centers. In addition, BHCHP connects with unsheltered homeless folks who sleep on the streets or in makeshift shelters under the bridges, down the alleys and behind the buildings of the city.The integrated care model at BHCHP unites physicians, physician assistants, nurse practitioners, nurses, case managers and behavioral health professionals in a close collaboration.", supervisor: "Cecilia Ibeabuchi", latitude: 42.352936, longitude: -71.062904)
        self.programs.append(program)
    }
    func Bridge() {
        let program = Program(name: "Bridge Over Troubled Waters", description: "Founded in 1970, the mission of Bridge Over Troubled Waters is to enable high-risk and homeless youth to achieve a healthy and productive adulthood through prevention, intervention, and education services. Bridge is the only agency in the Boston area to provide a continuum of age-appropriate services to runaway, homeless, and high-risk young people. Whether young people need assistance to communicate with a parent, maintain sobriety, earn a high school diploma, or find housing, Bridge helps each transition to a healthy adulthood. Bridge has grown into a structured multi-service agency with an array of services: street outreach, free medical and dental care, runaway services, counseling, alternative education, computer training program, workforce development, job search assistance, long term outpatient substance abuse counseling, transitional day program for homeless young adults and transitional living programs. Bridge works with youth that are 16 to 24 years old. Currently, Bridge serves approximately 5,000 youth each year.", supervisor: "Michael K Mengech", latitude: 42.355381, longitude: -71.063001)
        self.programs.append(program)
    }
    func CampusSchool() {
        let program = Program(name: "The Campus School at Boston College", description: "The Campus School at Boston College serves students ages 3-21 with multiple disabilities including complex health care needs. The program provides student centered, educational, and therapeutic services in a school based setting as well as consultation and training to local school systems and families. Using a transdisciplinary approach, student growth is achieved through the development of a stimulating environment and challenging instruction tailored to the needs of the individual.", supervisor: "Kathleen Houlihan", latitude: 42.333972, longitude: -71.168473)
        self.programs.append(program)
    }
    func CareerCollaborative() {
        let program = Program(name: "Career Collaborative", description: "Career Collaborative strives to help motivated, low-income adults gain employment in a field with career-potential. Their job-search program includes a four-week job-search/job-readiness class, an ongoing structured support group, and 20 practice interviews with volunteers from a variety of professions. In order to “graduate” from the program, participants must get and retain a steady job for a minimum of two years. Throughout these first two years of employment, Career Collaborative provides career coaching for participants to help facilitate their transition back into the workforce, and ensure they are receiving the exact support and assistance they need. Since its founding in 1997, Career Collaborative has helped over 1,825 families in the Boston area move toward economic self-sufficiency. Their mission is to help end working-class poverty by helping adults get and succeed at life-changing jobs, making Massachusetts and its families stronger.", supervisor: "Magdalena Lynch", latitude: 42.354274, longitude: -71.058873)
        self.programs.append(program)
    }
    func Casa() {
        let program = Program(name: "Casa Nueva Vida", description: "Casa Nueva Vida opened its doors in 1989 with the mission of helping our resident families gain the education and skills they need to permanently lift themselves out of poverty. Our programs are designed to provide our residents with the speciﬁc training and knowledge they need to so that their life goals of entering the workforce or continuing on to higher education become attainable. Thanks to our many friends and supporters, we have stabilized hundreds families since 1989. I hope that you place Casa Nueva Vida’s website among your favorites. Your friendship and support means so much to us as we continue our work of helping single mothers and their children achieve the stability and independence they work so hard to obtain. Thank you for taking the time from your busy schedule to read about our work with homeless families. We would be more than happy to hear from you.", supervisor: "Karin Cisterna", latitude: 42.308455, longitude: -71.101776)
        self.programs.append(program)
    }
    func Catholic() {
        let program = Program(name: "Catholic Charities Teen Center at St. Peters", description: "Catholic Charities Teen Center at St. Peter serves as a safe haven for adolescents living in Dorchester’s most troubled areas—the Bowdoin Street / Geneva Avenue neighborhood—during after school hours and throughout the summer months. The Teen Center is open to youths of all backgrounds and faiths; most members are from immigrant families from Cape Verde. It was newly arriving Cape Verdean families who, in partnership with Catholic Charities of Boston, opened the Teen Center in 2002. Close to 300 youths, ages 12-19 in grades 7-12, regularly access the Teen Center on an annual basis; more than 100 additional teens are served through sports tournaments each year. Most of the Teen Center “members” attend Boston Public schools.", supervisor: "Lucas Medina", latitude: 42.307859, longitude: -71.066822)
        self.programs.append(program)
    }
    func Charlesview() {
        let program = Program(name: "Charlesview Residences", description: "Charlesview, Inc. is dedicated to advancing the well-being of individuals and families and to promoting the diversity and vibrancy of the Allston-Brighton community. We do this by providing healthy, affordable homes; offering programs designed to enrich, educate and inspire; and engaging in innovative philanthropy. The Charlesview story is one of community empowerment, interfaith cooperation and collaborative public/private partnerships. Incorporated forty years ago, Charlesview was founded as a mixed-income housing resource for the community. The Josephine A. Fiorentino Community Center within Charlesview Residences offers a wide variety of programs and classes for families, children, adults, and elders. Moreover, this community center is not exclusively used by the members of Charlesview Residences, but also invites any members of the Allston-Brighton community to take part in their programming.", supervisor: "Jo-Ann Barbour", latitude: 42.369314, longitude: -71.140267)
        self.programs.append(program)
    }
    func CollabEd() {
        let program = Program(name: "Collaborative Educational Services", description: "Collaborative Educational Services provides educational services in the Elliot Youth Detention Facility for males ages 12-20 who are involved with the courts or who have been committed to the Department of Youth Services. The facility provides all the basic needs of food, housing, and security. In addition to the educational component designed to meet immediate needs, there is also a recreational program consisting of sports, outdoor recreation, movies, and games. Regular rap sessions and general house meetings round out the programs. It needs to be emphasized that the facility is a secure detention facility, and security is our first priority. Moreover, since the clients are juveniles, confidentiality is essential. Students should never provide last names, phone numbers, or mailing addresses to the clients. Finally, volunteers are never to discuss the details of any court case with a client.", supervisor: "Bill Cribben", latitude: 42.293177, longitude: -71.091127)
        self.programs.append(program)
    }
    func Collegebound() {
        let program = Program(name: "Collegebound Dorchester", description: "College Bound Dorchester works to ensure that all students view success in college not just as a possibility in their lives but as a baseline expectation. Everyday College Bound Dorchester’s educators work with diverse populations between 3 months to 27 years of age, including at-risk youth, newly arrived immigrants and families struggling to provide educational support to their children. In each program, College Bound Dorchester provides educational services to the under-served and lays the foundation for future academic, economic and social success. This work has the ability to not only increase the number of college graduates in Dorchester, but to also shift the community’s mindset about college. This shift, from one of limited possibilities to one of high aspirations for all, will ultimately have transformative impact on the community’s socioeconomic development. With an annual budget of $5.5 million and a staff of 80, College Bound Dorchester annually serves nearly 900 children, youth and adults.", supervisor: "Cheryl DiNatale", latitude: 42.291778, longitude: -71.064135)
        self.programs.append(program)
    }
    func Crossroads() {
        let program = Program(name: "Crossroads Family Center", description: "Crossroads was established in 1985 by the Most Holy Redeemer Parish and Father Bernard Mclaughlin. The doors first opened for a family displaced by a devastating fire and quickly expanded capacity and service in response to the growing phenomenon of family homelessness in East Boston. Today, Crossroads is a subsidiary of St. Mary’s Center for Women & Children. It provides shelter, case management, housing search, stabilization services, and food pantry assistance to homeless, formerly-homeless and low-income families. Crossroads is directed toward three objectives: personal goal attainment; socioeconomic mobility; and rapid re-housing for families served. Socioeconomic mobility is characterized by increased income, improved educational and occupational status, and increased social networks. The shelter program is home to 27 families (men, women, and children) referred to Crossroads by the Massachusetts Department of Housing and Community Development. Their main building houses the congregate shelter and food pantry. Crossroads also provides shelter services for 12 families housed in apartments in the immediate East Boston neighborhood. All 27 families engage in weekly, intensive case management and re-housing services as well as financial, parenting, and other self-sufficiency related workshops which are held on site.", supervisor: "Lauren Antonelli", latitude: 42.371374, longitude: -71.040043)
        self.programs.append(program)
    }
    func East() {
        let program = Program(name: "East Boston Neighborhood Health Center", description: "The East Boston Neighborhood Health Center is one of the largest community health centers in the country, providing services to the community for over 40 years. Serving an ethnically and culturally diverse community, EBNHC offers a complete range of services, from Pediatrics to Geriatrics. All students will have the opportunity to learn about the community of East Boston, the challenges faced by our predominately low income, immigrant community, as well as the challenges facing community health care.  And, most importantly, students will come to see the resiliency of our community and our health center.", supervisor: "Eileen Terchiak", latitude: 42.372544, longitude: -71.038336)
        self.programs.append(program)
    }
    func Elders() {
        let program = Program(name: "Elders Living at Home", description: "The Elders Living at Home Program at BMC was founded thirty years ago. The mission of the Elders Living At Home Program is to support elders in making the transition out of homeless, to provide supportive services that build on the individual abilities of elders and to help them overcome the barriers to permanent housing. They make every effort to reach out to those most in need, including non-English-speaking elders and other marginalized individuals. We are committed to providing high-quality services in a respectful manner that will help each client reach his or her highest potential. The Elders Living at Home Program strives to be a model for service, advocacy, research and education on the causes of and solutions to elder homelessness. 90% of the clients they have worked to have maintained their housing in the face of imminent homelessness, making this program one of the key go-to agencies for Boston area attorneys representing elders facing eviction, for housing management companies seeking solutions to avoid beginning the eviction process and even for the courts themselves looking for solutions to the growing problem of seniors losing their homes.", supervisor: "Kip LangelloKip Langello", latitude: 42.338031, longitude: -71.070898)
        self.programs.append(program)
    }
    func EDG() {
        let program = Program(name: "Educational Development Group", description: "The mission of Educational Development Group is to prepare new immigrants for success by providing them with the language skills and cultural awareness needed to access educational and employment opportunities. To fulfill our mission, the cornerstone of our program is training in English communication, and reading and writing skills.", supervisor: "Frances Laroche", latitude: 42.341104, longitude: -71.081858)
        self.programs.append(program)
    }
    func HAPHI() {
        let program = Program(name: "Haitian American Public Health Initiatives", description: "HAPHI is a minority run, non-profit agency dedicated to providing members of the Haitian-American community in Metro Boston with culturally and linguistically accessible information and services to improve their health and wellbeing. Located in Mattapan, HAPHI was founded in 1989 by a group of Haitian-American health care professionals to address pressing public health issues confronting Boston's Haitian community. HAPHI’s mission is to bridge the gaps in services to facilitate Haitian immigrants’ integration into the American mainstream society, as well as to promote the health and well-being of the Haitian community. HAPHI is committed to work with and for the Haitian community in the areas of culturally appropriate health education and support, advocacy for access to care, and in creating opportunities for economic development. HAPHI provides English as a Second Language (ESL) and Citizenship Classes for the Haitian community. The Adult Education program run by volunteers enables Haitian immigrants to acquire the necessary skills that will allow them to positively integrate into the American mainstream. They also have computer literacy classes for children with special needs, social/recreational and academic enrichment  activities for the disabled and non-disabled youth, and Parent Education Empowerment activities for families with children with special needs. They hold monthly support group/education workshops and provide community outreach and education.", supervisor: "Renald Raphael", latitude: 42.269425, longitude: -71.094017)
        self.programs.append(program)
    }
    func Haley() {
        let program = Program(name: "Haley House", description: "Haley House is dedicated to helping those made vulnerable by the harshest effects of inequality move toward wholeness and economic independence. We offer collaborative living and working environments that: Build communities and connections across boundaries, Model creative alternatives that confirm the intrinsic dignity and worth of each person, Challenge the attitudes and structures that perpetuate suffering. Haley House carries the philosophy of personalism from its Catholic Worker roots, compelling us to take personal responsibility for individuals in need. People in and around the community resist violence and injustice by taking direct action and promoting justice and peace through their own life choices. Hospitality is key to the community’s way of life. We share friendship, space, and material goods that we have received through the generosity of others.Honoring our roots as a house of hospitality, Haley House today addresses basic human needs through four interconnected branches: direct services (soup kitchen, food pantry, elder meal, and clothing room); housing; urban farming; Haley House Bakery Cafe; Dudley Dough.", supervisor: "Andrew Bishop", latitude: 42.343979, longitude: -71.073948)
        self.programs.append(program)
    }
    func Italian() {
        let program = Program(name: "The Italian Home for Children", description: "At Italian Home for Children, we are creating communities where all children, adults, and families are embraced and empowered to reach their full potential. Italian Home for Children provides progressive and therapeutic programs to help children, adults, and families with emotional, behavioral, and educational special needs thrive in their communities.", supervisor: "Jane Zopatti-Lewis", latitude: 42.302576, longitude: -71.126681)
        self.programs.append(program)
    }
    func James() {
        let program = Program(name: "James Otis Elementary School", description: "The mission of the James Otis School, working in concert with families and other community agencies, is to provide a challenging instructional program designed to promote intellectual and social development of every child. These programs will be designed so that the students will develop a capacity and a sustaining desire for lifelong learning which will enable them to enjoy successful participation as productive and responsible citizens in a democratic society. The James Otis Elementary has a diverse and dedicated group of highly qualified teachers that reflect the diversity of our student population. The goal of James Otis Elementary is to push children to succeed academically by helping schools become centers for the development of children and families and by infusing the school with a family literacy approach. Within the Otis School, parents are given a chance to study English as a second language in the school while simultaneously learning how to advocate for their children. The children, few of whom spoke English before entering the school, are provided with individualized programs.  Students also enjoy a full complement of art, music, theater, science, drama, physical education, Spanish and computers.", supervisor: "Mara DosSantos", latitude: 42.375493, longitude: -71.033874)
        self.programs.append(program)
    }
    func JVS() {
        let program = Program(name: "Jewish Vocational Services", description: "For over 75 years JVS has helped people secure financial independence. Every year, JVS serves nearly 21,000 individuals providing them the skills they need to gain employment, as well as to progress up the career and wage ladder and make sound financial choices over their lifetimes. Programs span from providing employment services to Refugees, to educational programs that help their students prepare for college or become certified in the Biotechnology, Nursing, and Pharmacy fields. JVS was founded in 1938 during the Great Depression to assist Jewish immigrants struggling to enter the American workforce and support their families. Today, they serve a diverse clientele that represent over 67 nations and speak 59 languages, helping them change their lives by finding employment and building careers. Their mission is to empower individuals from diverse communities to find employment and build careers, while partnering with employers to hire, develop, and retain productive workforces. This is accomplished through the core values of learning, partnership, quality, respect, and social justice.", supervisor: "Amy Stein", latitude: 42.355073, longitude: -71.056597)
        self.programs.append(program)
    }
    func Little() {
        let program = Program(name: "Little Brothers Friends of the Elderly", description: "Little Brothers-Friends of the Elderly (LBFE) is an international, non-profit, volunteer-based organization committed to relieving isolation and loneliness among the elderly. LBFE is founded on the philosophy of flowers before bread, emphasizing the importance of nurturing the spirit as well as the body. LBFE has been serving Boston elders since 1979. PULSE students will support the City Sites program, which aims to create connections across generations by connecting volunteers from local universities to elder residents in subsidized and low income senior living communities around Boston through weekly intergenerational gatherings.", supervisor: "Airlie Parham", latitude: 42.310799, longitude: -71.103840)
        self.programs.append(program)
    }
    func Nativity() {
        let program = Program(name: "Nativity Preparatory School", description: "Nativity Preparatory School is an accredited, tuition-free, Jesuit middle school serving boys of all faiths from low-income families residing in Boston. Staffed by experienced teachers and dedicated volunteers who work closely with families, the school prepares students for success in high school and college. Nativity academically challenging and highly structured environment helps students grow in a love for learning and an abiding sense of responsibility to their community. In the Jesuit tradition, the school promotes the intellectual, spiritual, social, and physical growth that inspires boys from Boston to become men for others.", supervisor: "Meredith Smith", latitude: 42.321794, longitude: -71.101734)
        self.programs.append(program)
    }
    func NWWC() {
        let program = Program(name: "Newton Wellesley Weston Committee: Juniper House & Coyne Road", description: "Community Living, Inc. (NWW) has served individuals with intellectual and developmental disabilities and their families since 1972. NWW's mission is threefold: to offer a spectrum of local services to people with intellectual and developmental disabilities, to offer support services to their families, and to offer programs to increase community awareness and receptivity regarding persons with disabilities. Juniper House is one of six NWW Committee community residences for up to seven women who have intellectual and developmental disabilities. Coyne Rd. is another group home in the Waban neighborhood of Newton, accessible by public transportation. Coyne also has seven residents, 3 men and 4 women, and is run much like Juniper. Support services include 24-hour staffing, transportation to appointments and recreational activities, medical and financial assistance, skill development and community integration activities. Each resident also participates in a day program, works in a supported setting or competitive job, or enjoys retirement activities.", supervisor: "Alessia Baker", latitude: 42.351905, longitude: -71.186891)
        self.programs.append(program)
    }
    func NotreDame() {
        let program = Program(name: "Notre Dame Education Center", description: "Notre Dame Education Center is committed to social justice and to leveling the playing field for all. This is in essence what NDEC accomplishes by providing quality education and support services to students ages 16-80 in and around the Boston area. NDEC's programs include: ESOL, Adult Basic Education (ABE) courses, High School Diploma and HiSET certificate programs, Citizenship classes, job and workforce training, Distance Learning, and more! Each year, more than 400 students come to the Center seeking academic achievement, career advancement, and community. Many of our students have immigrated to the United States from over 40 different countries around the world while some of our students grew up in Boston. To meet the needs of different learners’ goals and prior academic experiences, NDEC provides individualized pathways with a wide range of programs and services.", supervisor: "Mary Kate Schmermund", latitude: 42.333396, longitude: -71.053731)
        self.programs.append(program)
    }
    func Paraclete() {
        let program = Program(name: "Paraclete Inc.", description: "The Paraclete Academy Afterschool Program fosters the intellectual, moral, social, and creative growth of its students and nurtures the full potential of their whole character. We do this in a number of ways: we balance high expectations with an unfailingly positive culture; we practice project and game-based learning in classes that actively engage students and emphasize hands-on activities; we keep classes small to provide a large amount of individual attention to student needs; and we design our curriculum to align with that of the Boston Public Schools in order to reinforce the material that students learn during their school days and to enrich what cannot be explored daily in school. The program’s faculty, staff, and volunteers work closely with students’ families to build a supportive and caring community. We develop personal and institutional support that will ensure the continuing success of Paraclete students in high school and beyond. Everyone involved in The Paraclete Afterschool Program contributes time, energy, and talent to our community. Parents and community members volunteer their time and expertise to help provide the myriad of services that we need to continue to function. Paraclete Academy students are expected to uphold high standards of academic achievement, conduct, and respect for others. Much is expected of our students and, in return, much can be gained from our program.", supervisor: "Allison Maladore", latitude: 42.334961, longitude: -71.052346)
        self.programs.append(program)
    }
    func Pine() {
        let program = Program(name: "Pine Street Inn", description: "The mission of Pine Street Inn is to be a community of respect and hope for each guest it serves; to be a resource through which neighbors and friends can help to meet the basic needs of others; and to serve as a national leader in the fight to end homelessness. Pine Street Inn is a 501(c) 3 non-profit organization.", supervisor: "Bruce Burleson, Scottie Wait", latitude: 42.343400, longitude: 71.064502)
        self.programs.append(program)
    }
    func PBread() {
        let program = Program(name: "Project Bread", description: "Project Bread brings a fresh approach to ending hunger. These are our goals: to promote sustainable and reliable access to healthy food for all, to invest in the strength and resiliency of local communities, and to collaborate with others in building a robust regional food system. As the only statewide anti-hunger organization, we listen and learn, identify needs and opportunities, and connect people, resources, and programs—in ways both tried and new. Since 1969, The Walk for Hunger has been a tradition in Massachusetts. Today, the Walk has become the country's oldest continual pledge walk and the largest one-day fundraiser focused on alleviating hunger. On the first Sunday in May each year, more than 40,000 Walkers and 2,000 Volunteers join together to make a difference in the lives of our neighbors. The 20-mile Walk for Hunger begins on the Boston Common, and winds through Boston, Brookline, Newton, Watertown, and Cambridge. Project Bread's toll-free FoodSource Hotline is the only comprehensive statewide information and referral service in Massachusetts for people facing hunger. The toll-free Hotline responds to more than 46,000 calls a year from people across Massachusetts struggling to feed their families.", supervisor: "Khara Burns", latitude: 42.373949, longitude: -71.040448)
        self.programs.append(program)
    }
    func PPlace() {
        let program = Program(name: "Project Place", description: "The mission of Project Place is to promote hope and opportunity for homeless and low-income individuals by providing the skills, education and resources needed to obtain stable employment and housing. Students who volunteer at Project Place can expect to gain a new perspective on the magnitude of the challenges homeless adults face beyond their financial need. Whether those challenges are language barriers, learning disabilities, a lack of formal education, mental health issues and/or criminal records, Project Place is prepared to help clients find a way to meet all of their needs.", supervisor: "Chris James", latitude: 42.344117, longitude: -71.066343)
        self.programs.append(program)
    }
    func Rosie() {
        let program = Program(name: "Rosie's Place", description: "Rosie's Place was founded in 1974 as the first women’s shelter in the United States. The organization’s mission is to provide a safe and nurturing environment that helps poor and homeless women maintain their dignity, seek opportunity, and find security in their lives. Today, Rosie’s Place not only provides meals and shelter but also creates answers for 12,000 women a year through wide ranging support, housing, and education services. Rosie’s Place relies solely on the generous support of individuals, foundations and corporations and does not accept any city, state or federal funding. They are committed to the fight for social justice. At Rosie’s Place, when a woman comes through the door in need of a meal, it usually means she needs more than food. As there is no single cause of poverty and homelessness, consequently there is no single cure-all. Every year, Rosie’s Place meets thousands of poor and homeless women with thousands of unique needs and challenges. Some can be remedied immediately and some will be long-term processes. Rosie’s Place is able to help all of these women—unconditionally—for as long as they need it.", supervisor: "Jessica Garretson", latitude: 42.334287, longitude: -71.076976)
        self.programs.append(program)
    }
    func Roxbury() {
        let program = Program(name: "Roxbury Youth Program", description: "Roxbury Youth Program is run under the broader Unitarian Universalist Urban Ministry—one of the oldest faith-based social service organizations in the country. The UU Urban Ministry embraces a philosophy of direct engagement to empower Boston's disadvantaged residents; it is part of the Urban Ministry's work to bring people together across differences of ethnicity, culture, and socioeconomic background to learn from one another and work toward common goals. Based in a belief in social justice and respect for the dignity of every individual, all Urban Ministry programs are nonsectarian. The Roxbury Youth Program is an after-school program focused on academic achievement and character development. We strive to provide a safe environment where students are encouraged to challenge themselves and their perceived boundaries and limitations. During the program, our 8th-12th grade students will receive academic support and enjoy an “evening enrichment curriculum” focusing on positive self-image, college readiness, and life skills.", supervisor: "Marvin Venay", latitude: 42.330238, longitude: -71.089423)
        self.programs.append(program)
    }
    func Samaritans() {
        let program = Program(name: "Samaritans Inc.", description: "Samaritans, Inc. is a non-profit, non-religiously affiliated, suicide prevention center. Since 1974, we have worked to reduce the incidence of suicide and to alleviate feelings of isolation through our 24/7/365 crisis services. These lines are staffed entirely by trained volunteers (befrienders) to offer compassionate, non-judgmental listening and support to lonely, depressed and suicidal individuals. Befrienders do not give advice or try to solve the problems of the users of our services. Rather, by offering unqualified respect and caring, befrienders seek to understand their feelings and, in doing so, briefly share a burden that has become too heavy. Befrienders do not aim to fix but rather offer respite. Volunteers must be able to listen well and to reserve judgment. They must also be willing to hear about suicide and death and be able to remain calm during crises.", supervisor: "Aram Seo", latitude: 42.355298, longitude: -71.062620)
        self.programs.append(program)
    }
    func Scholar() {
        let program = Program(name: "Scholar Athletes", description: "The mission of Scholar Athletes (SA) is to reduce the opportunity gap for public high school students by supporting academic achievement through athletics.  We focus on 3 core program areas: Academic Coaching & Mentoring, Health & Wellness, and Postsecondary Planning supporting our Zone members on and off the field.  We strive to enhance the scholar-athlete experience by connecting our Zone members to dedicated and trained staff and volunteers to improve academic success and personal growth. Scholar Athletes operates 23 school-based learning centers called ‘Zones’ in Boston, Springfield and Everett to respond to the mounting needs of young people in our cities. Scholar Athletes Zones provided academic support, workspace and supplies along with technology resources. This space and our dedicated staff enable Zone members to stay on track both on and off the field providing them the resources and supports needed to excel beyond high school.  SA also engages students in Health & Wellness programs that include intramural sports leagues and other physical activities through our We Are Fit program.", supervisor: "Allison Rogers", latitude: 42.326641, longitude: -71.071840)
        self.programs.append(program)
    }
    func StFrancis() {
        let program = Program(name: "St. Francis House", description: "St. Francis House is the largest day shelter in New England. Located in the heart of downtown Boston, we serve more than 500 poor and homeless men and women a day, 365 days a year. Our basic, rehabilitative, and housing services overlap and build on one another to provide our guests with continuous and comprehensive care. For more than 30 years, we have welcomed poor and homeless men and women who fear that their best days are behind them. We provide services, support, and a glimpse of what their lives can become: productive, healthy, fulfilling. St. Francis House is nonprofit and nonsectarian. Our mission and approach are simple: We believe in the worth of every human being, and we know from experience that when people have the right tools, change can happen. Big change. That’s why we provide our guests with everything they need to reclaim their dignity and rebuild their lives: nutritious meals, clothing, access to medical care, counseling, vocational rehabilitation, and housing.", supervisor: "Ashley Medlar", latitude: 42.352920, longitude: -71.062980)
        self.programs.append(program)
    }
    func StMarks() {
        let program = Program(name: "St. Mark Community Education Program", description: "The St. Mark Community Education Program’s mission is to build a vibrant and flourishing community by providing English language and Citizenship educational skill development and access that adult immigrants and their families need to fully participate in the U.S. society. Their vision is that the St. Mark Parish area is populated with adult immigrants who are able to communicate in English and have become citizens so that they are able to fully participate in U.S. society, including voting. The program currently serves people from Vietnam, Cape Verde, Haiti, Central America, Dominican Republic, the Middle East and Africa. SMCEP was founded in the late ‘90s. The priest at the time was involved in social activism, and wanted people to vote, but found that a lot of people living in the area did not speak English. Therefore, the program began as informal English classes. They later received funding from English for New Bostoniants. In 2012, they became a 501(c)(3) organization. Their services include: Four levels of ESOL classes, citizenship classes, support for achieving naturalization, link people with support services, help people find and get further education and jobs, work with other agencies to help students. As students improve their English , they can advocate for themselves and their families, gain better employment, further their education, participate in the U.S. political process and public life, and negotiate their interactions with government, public and private institutions.", supervisor: "Mark Oliver", latitude: 42.292462, longitude: -71.064329)
        self.programs.append(program)
    }
    func StMarys() {
        let program = Program(name: "St. Mary's Center for Women & Children", description: "St. Mary’s Center for Women and Children offers innovative and family-centered programs for women and children who have experienced trauma and are living in poverty. Placing families at the center of our efforts, St. Mary’s Center works in partnership with young women, many of them mothers, to break the intergenerational cycle of poverty and achieve lasting, powerful change by building their emotional well-being, educational achievements and economic independence.", supervisor: "Shannon Kearns", latitude: 42.314150, longitude: -71.063437)
        self.programs.append(program)
    }
    func StStephens() {
        let program = Program(name: "St. Stephen's After School Program", description: "Since 2000, St. Stephen’s Youth Programs has been providing young people from some of Boston's most disadvantaged communities with year-round, out-of-school time academic enrichment. The school year portion of our year-round programming, B-READY, provides elementary and middle school students with a safe, fun place to go after school and receive academic and emotional support. PULSE students have the option to serve in either the Elementary or Middle School program.", supervisor: "Sandy Quispe", latitude: 42.340602, longitude: -71.073851)
        self.programs.append(program)
    }
    func Suffolk() {
        let program = Program(name: "Suffolk County House of Correction", description: "The Suffolk County House of Correction is a secure facility located in the City of Boston. Administered by Suffolk County Sheriff Steven Tompkins, the facility provides for the care, custody, and control of over 1800 male and female inmates most of whom have been sentenced for 2 1/2 years or less. Under the Sheriff's leadership, the House of Correction offers a multitude of social service and educational programs aimed at reducing recidivism by assisting inmates in acquiring the necessary skills and behaviors to lead independent, productive, and law-abiding lives. The House of Correction's Education Department offers an extensive array of programs which are organized to support the department's four major goals: literacy instruction; high school diploma or HISET preparation; college programs; and employment training.", supervisor: "Bob Moran", latitude: 42.334501, longitude: -71.067912)
        self.programs.append(program)
    }
    func Tenacity() {
        let program = Program(name: "Tenacity", description: "Tenacity provides a pathway to post-secondary success for underserved urban youth. From ages six through college, our core offerings engage over 5,000 youth annually with a focused approach to making education relevant and graduation achievable. PULSE students will serve at Tenacity’s Middle School Academy at the John W. McCormack location. Tenacity’s Middle School Academy is an intensive three-year program (6th -8th grade) that works to improve students’ literacy, tennis, and fitness skills, while simultaneously building character and engaging families.", supervisor: "Paula Coyle", latitude: 42.318007, longitude: -71.043876)
        self.programs.append(program)
    }
    func United() {
        let program = Program(name: "United South End Settlements", description: "For generations, the South End and Lower Roxbury community has been home to families of all backgrounds, a refuge for the city’s artistic soul, and at the forefront of opening doors for residents and guests regardless of their sexual orientation, class or religion. United South End Settlements (USES) was founded in 1891 as the first settlement house in Boston when members of the community committed to ensuring that all residents had what they needed to move forward.  This was the beginning of the early social justice movement. USES is a “living room” for our community – a place where all residents can come together to continue their education, build a collective voice, and receive the support they need elevate themselves and each other. USES provides services for people across the lifespan; PULSE students will work specifically in the Early Childhood Education Program or the after-school program Club 48.", supervisor: "Melody Valdes", latitude: 42.340052, longitude: -71.076419)
        self.programs.append(program)
    }
    func VPBLC() {
        let program = Program(name: "Victory Programs: Boston Living Center", description: "Boston Living Center (BLC) The Boston Living Center is a nonprofit community resource center committed to fostering the wellness of all HIV positive people and responding to the changing needs of the HIV/AIDS community. Through peer leadership and support, BLC strives to enhance and enrich the lives of our members by providing education, treatment information and support services with the goal of empowering members to live productive lives and participate within their families and communities. The Boston Living Center provides programs and services, free-of-charge, to members in the context of an exceptionally welcoming, drug-free, safe, confidential, and culturally diverse environment. The only criterion for membership at the Center is verification of HIV+ status.", supervisor: "Eli Feliciano", latitude: 42.348844, longitude: -71.073095)
        self.programs.append(program)
    }
    func VPLarc() {
        let program = Program(name: "Victory Programs: Larc & Women's Hope", description: "Living and Recovering Community (LARC): LARC is located at the Shattuck Hospital in Jamaica Plain.  This program provides up to 90 days of specialized substance use disorder treatment and stabilization services for up to 20 men and women.  The residents at LARC are people living with HIV/AIDS with histories of substance use disorders and chronic relapse. Many have experienced barriers in their lives related to these and other physical and mental health diagnoses.  LARC residents are typically homeless or at risk of homelessness.  Through this program, LARC residents are fully integrated into a supportive community and receive individualized treatment for recovery. Women’s Hope is located at the Lemuel Shattuck Hospital in Jamaica Plain and provides up to 28 days of specialized residential treatment program for women addressing substance use disorders. Many of the women who go through our program are also living with HIV/AIDS, mental health disorders or other chronic conditions. Our program can accommodate up to 32 women including pregnant and postpartum women. Designed specifically for women, our case management and addiction recovery support team helps our residents build self-awareness and confidence as they continue in their own recovery.", supervisor: "Danette Caruso, Zanele McIntyre", latitude: 42.300335, longitude: -71.101879)
        self.programs.append(program)
    }
    func VPShepherd() {
        let program = Program(name: "Victory Programs: Shepherd House", description: "Located in Dorchester, Shepherd House is a residential treatment program for women dealing with substance use disorders. Our 4 to 8 month program can serve up to 32 women and provides residents with a bridge between treatment and reintegration into community living as they move through their own recovery. Shepherd House and its three side-by-side recovery sites is one of Massachusetts’ most dynamic leaders in innovative, evidenced-based practices of care and support for women in recovery.", supervisor: "Angela Headley", latitude: 42.314303, longitude: -71.062593)
        self.programs.append(program)
    }
    func VPVictory() {
        let program = Program(name: "Victory Programs: Victory House", description: "Victory House provides residential treatment services to men, and now women, diagnosed with substance use disorder who may also deal with health issues such as HIV/AIDS, mental health issues and head injuries. Our 4 to 8 month residential treatment program can accommodate up to 25 male residents. The program is based on a harm reduction model. Clients participate in both in-house and outside recovery meetings. As they transition through the different levels of the program, the clients take steps to secure resources such as schooling, jobs, housing, etc. They also have a female house which at full capacity is currently 10 beds but will hopefully soon be 14 beds.", supervisor: "Ryan McCallister", latitude: 42.338150, longitude:  -71.078361)
        self.programs.append(program)
    }
    func WestEnd() {
        let program = Program(name: "West End House", description: "The West End House Boys & Girls Club is an independent Boys and Girls Club in the City of Boston that has been transforming the lives of immigrant and urban youth since its founding in 1906. A century ago, many of our members were the sons of immigrants escaping the pogroms of Eastern Europe. Today, they are the sons and daughters of immigrants from the Dominican Republic, China, Vietnam, Haiti, Cape Verde and three dozen other countries, often fleeing political unrest and poverty to seek a better life for their children in the U.S. With 75% of West End House families earning less than $25,000 per year and 70% of the young people served coming from single-parent households, the West End House is truly reaching the children and teens most in need. The membership fee is only $15 annually, to ensure there are no financial barriers to participation. Even with such a low fee, more than half of the young people are provided scholarships by the West End House. The West End House offers its 1,500 members an integrated array of programs across four broad areas: leadership and life skills; academic support and college preparation; sports, fitness and nutrition; and visual and performing arts. In support of these programs, the West End House also serves over 1,200 healthful hot meals to members every week. The West End House offers a rich array of activities, support services and emotional connections delivered by an expert staff that understands the profound effect consistent, nurturing, stable relationships have on a child's life. The West End House transforms lives by connecting members with the activities, resources and supports they need to succeed inside and outside of school.", supervisor: "Sunny Harirchi", latitude: 42.350178, longitude:  -71.137192)
        self.programs.append(program)
    }
    func WFYP() {
        let program = Program(name: "Work Force Youth Program", description: "The Work Force is a comprehensive post-secondary prep after-school educational enrichment and work-readiness program for low-income teens living in Cambridge public housing. Holistic in design, the program provides participants with sustained networks of learning and support over a critical five-year span: from the eighth grade through high school graduation. Our goal is to help our over 200 participants to acquire the wide range of skills necessary for long-term success.", supervisor: "Carmen Blyden, Kam Maali", latitude: 42.393641, longitude: -71.134958)
        self.programs.append(program)
    }
}
